# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
 workflow_dispatch:
 push:
  tags:
   - '*'

jobs:
  publish-gpr:
    uses: toyfield/actions/.github/workflows/pnpm-install-npm-publish.yaml@main
    permissions:
      contents: read
      packages: write